iv-lab5/iv-lab5/Models/ErrorViewModel.cs
using System;

namespace iv_lab5.Models
{
	public class ErrorViewModel
	{
		public string RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

iv-lab5/iv-lab5/Models/Lab1DataModel.cs
namespace iv_lab5.Models
{
	public class Lab1DataModel
	{
		public string InputLine { get; set; }
		public string ErrorValue { get; set; }
		public string Response { get; set; }
		public string Calculated { get; set; }
	}
}

iv-lab5/iv-lab5/Models/Lab2DataModel.cs
namespace iv_lab5.Models
{
	public class Lab2DataModel
	{
		public string InputNumber { get; set; }
		public string ErrorValue { get; set; }
		public string Response { get; set; }
		public string Calculated { get; set; }
	}
}

iv-lab5/iv-lab5/Models/Lab3DataModel.cs
namespace iv_lab5.Models
{
	public class Lab3DataModel
	{
		public string FirstInputLine { get; set; }
		public string SecondInputLine { get; set; }
		public string ThirdInputLine { get; set; }
		public string FourthInputLine { get; set; }
		public string FifthInputLine { get; set; }
		public string SixthInputLine { get; set; }
		public string SeventhInputLine { get; set; }
		public string EighthInputLine { get; set; }
		public string ErrorValue { get; set; }
		public string Response { get; set; }
		public string Calculated { get; set; }
	}
}

iv-lab5/iv-lab5/Models/UserProfileModel.cs
namespace iv_lab5.Models
{
	public class UserProfileModel
	{
		public string Email { get; set; }
		public string UserName { get; set; }
		public string EmailVerified { get; set; }

	}
}

iv-lab5/iv-lab5/Controllers/AccountController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authentication;
using Okta.AspNetCore;
using iv_lab5.Models;
using System.Linq;

namespace iv_lab5.Controllers
{
	public class AccountController : Controller
	{
		[HttpGet]
		public IActionResult SignIn()
		{
			if (!HttpContext.User.Identity.IsAuthenticated)
			{
				return Challenge(OktaDefaults.MvcAuthenticationScheme);
			}
			return RedirectToAction("Index", "Home");
		}

		[HttpPost]
		public IActionResult SignOut()
		{
			return new SignOutResult(
				new[]
				{
					OktaDefaults.MvcAuthenticationScheme,
					CookieAuthenticationDefaults.AuthenticationScheme,
				},
				new AuthenticationProperties { RedirectUri = "/Home/" });
		}

		[HttpGet]
		public IActionResult Profile()
		{
			return View(new UserProfileModel()
			{
				UserName = HttpContext.User.Claims.FirstOrDefault(x => x.Type == "name").Value.ToString(),
				Email = HttpContext.User.Claims.FirstOrDefault(x => x.Type == "email").Value.ToString(),
				EmailVerified = HttpContext.User.Claims.FirstOrDefault(x => x.Type == "email_verified").Value.ToString()
			});
		}
	}
}

iv-lab5/iv-lab5/Controllers/HomeController.cs
using iv_lab5.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace iv_lab5.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

iv-lab5/iv-lab5/Controllers/LabsController.cs
using iv_lab5.Models;
using LabsLibrary;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Diagnostics;

namespace db_lab5.Controllers
{
	[Authorize]
	public class LabsController : Controller
	{
		private readonly ILogger<LabsController> _logger;

		public LabsController(ILogger<LabsController> logger)
		{
			_logger = logger;
		}

		public IActionResult Lab1()
		{
			return View();
		}

		[HttpPost]
		public IActionResult Lab1(Lab1DataModel model)
		{
			var labRunner = new Lab1Runner(model.InputLine);

			try
			{
				model.Calculated = labRunner.RunLab();
			}
			catch (ArgumentException e)
			{
				model.ErrorValue = e.Message;
			}
			catch (Exception e)
			{
				model.ErrorValue = e.Message;
			}

			return View(model);
		}

		public IActionResult Lab2()
		{
			return View();
		}

		[HttpPost]
		public IActionResult Lab2(Lab2DataModel model)
		{
			var labRunner = new Lab2Runner(model.InputNumber);

			try
			{
				model.Calculated = labRunner.RunLab();
			}
			catch (ArgumentException e)
			{
				model.ErrorValue = e.Message;
			}
			catch (Exception e)
			{
				model.ErrorValue = e.Message;
			}

			return View(model);
		}

		public IActionResult Lab3()
		{
			return View();
		}

		[HttpPost]
		public IActionResult Lab3(Lab3DataModel model)
		{
			var labRunner = new Lab3Runner(model.FirstInputLine, model.SecondInputLine, model.ThirdInputLine, model.FourthInputLine,
				model.FifthInputLine, model.SixthInputLine, model.SeventhInputLine, model.EighthInputLine);

			try
			{
				model.Calculated = labRunner.RunLab();
			}
			catch (ArgumentException e)
			{
				model.ErrorValue = e.Message;
			}
			catch (Exception e)
			{
				model.ErrorValue = e.Message;
			}

			return View(model);
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

iv-lab5/iv-lab5/Views/Home/Index.cshtml
@{
	ViewData["Title"] = "Home Page";
}

<div class="text-center">
	<h1 class="display-4">Ivan Nochovkin</h1>
	<h1 class="display-4">Faculty of Informational Technologies</h1>
	<h1 class="display-4">Student of IPZ-43 group</h1>
</div>

iv-lab5/iv-lab5/Views/Labs/Lab1.cshtml
@model Lab1DataModel

@{
	ViewData["Title"] = "First one";
}

<h1>@ViewData["Title"]</h1>
<text> &nbsp; &nbsp; &nbsp;</text>
<h2>It is necessary to implement an efficient algorithm for calculating the function F, which will have time to find any of its values ​​in less than one second.</h2>

<text> &nbsp; &nbsp; &nbsp;</text>

<form method="post" enctype="multipart/form-data" asp-controller="Labs" asp-action="Lab1">
	<div class="form-group">
		<label for="psize">Input line</label>
		<input type="text" class="form-control" id="inputLine" asp-for="InputLine">
	</div>
	<button type="submit" class="btn btn-primary mt-3">Submit</button>
</form>

<text> &nbsp; &nbsp; &nbsp;</text>
<text> &nbsp; &nbsp; &nbsp;</text>

@if (Model != null)
{
	<div class="container mt5">
		<div class="form-group">
			<h2 class="control-label">Lab1 output: @(Model != null ? Model.Calculated : string.Empty)</h2>
		</div>
		@if (Model != null && !string.IsNullOrEmpty(Model.ErrorValue))
		{
			<div class="row">
				<label for="perror"></label>
				<input type="text" id="perror" value="@Model.ErrorValue">
			</div>
		}
	</div>
}

iv-lab5/iv-lab5/Views/Labs/Lab2.cshtml
@model Lab2DataModel

@{
	ViewData["Title"] = "Second one";
}

<h1>@ViewData["Title"]</h1>
<text> &nbsp; &nbsp; &nbsp;</text>
<h2>Return the least number of operations resulting in one</h2>

<text> &nbsp; &nbsp; &nbsp;</text>

<form method="post" enctype="multipart/form-data" asp-controller="Labs" asp-action="Lab2">
	<div class="form-group">
		<label for="psize">Input your number</label>
		<input type="text" class="form-control" id="inputNumber" asp-for="InputNumber">
	</div>
	<button type="submit" class="btn btn-primary mt-3">Submit</button>
</form>

<text> &nbsp; &nbsp; &nbsp;</text>
<text> &nbsp; &nbsp; &nbsp;</text>

@if (Model != null)
{
	<div class="container mt5">
		<div class="form-group">
			<h2 class="control-label">Lab2 output: @(Model != null ? Model.Calculated : string.Empty)</h2>
		</div>
		@if (Model != null && !string.IsNullOrEmpty(Model.ErrorValue))
		{
			<div class="row">
				<label for="perror"></label>
				<input type="text" id="perror" value="@Model.ErrorValue">
			</div>
		}
	</div>
}

iv-lab5/iv-lab5/Views/Labs/Lab3.cshtml
@model Lab3DataModel

@{
	ViewData["Title"] = "Third one";
}

<h1>@ViewData["Title"]</h1>
<text> &nbsp; &nbsp; &nbsp;</text>
<h2>You need to output one number - the desired number of builders</h2>

<text> &nbsp; &nbsp; &nbsp;</text>

<form method="post" enctype="multipart/form-data" asp-controller="Labs" asp-action="Lab3">
	<div class="form-group">
		<label for="psize">First line</label>
		<input type="text" class="form-control" id="line" asp-for="FirstInputLine">
	</div>
	<div class="form-group">
		<label for="pdata">Second line</label>
		<input type="text" class="form-control" id="line" asp-for="SecondInputLine">
	</div>
	<div class="form-group">
		<label for="pdata">Third line</label>
		<input type="text" class="form-control" id="line" asp-for="ThirdInputLine">
	</div>
	<div class="form-group">
		<label for="pdata">Fourth line</label>
		<input type="text" class="form-control" id="line" asp-for="FourthInputLine">
	</div>
	<div class="form-group">
		<label for="pdata">Fifth line</label>
		<input type="text" class="form-control" id="line" asp-for="FifthInputLine">
	</div>
	<div class="form-group">
		<label for="pdata">Sixth line</label>
		<input type="text" class="form-control" id="line" asp-for="SixthInputLine">
	</div>
	<div class="form-group">
		<label for="pdata">Seventh line</label>
		<input type="text" class="form-control" id="line" asp-for="SeventhInputLine">
	</div>
	<div class="form-group">
		<label for="pdata">Eighth line</label>
		<input type="text" class="form-control" id="line" asp-for="EighthInputLine">
	</div>
	<button type="submit" class="btn btn-primary mt-3">Submit</button>
</form>

<text> &nbsp; &nbsp; &nbsp;</text>
<text> &nbsp; &nbsp; &nbsp;</text>

@if (Model != null)
{
	<div class="container mt5">
		<div class="form-group">
			<h2 class="control-label">Lab3 output: @(Model != null ? Model.Calculated : string.Empty)</h2>
		</div>
		@if (Model != null && !string.IsNullOrEmpty(Model.ErrorValue))
		{
			<div class="row">
				<label for="perror"></label>
				<input type="text" id="perror" value="@Model.ErrorValue">
			</div>
		}
	</div>
}

iv-lab5/iv-lab5/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - CP5</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/iv-lab5.styles.css" asp-append-version="true" />
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
			<div class="container-fluid">
				<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">L5-info</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>

				@if (User.Identity.IsAuthenticated)
				{
					<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
						<ul class="navbar-nav flex-grow-1">
							<li class="nav-item">
								<a class="nav-link text-dark" asp-area="" asp-controller="Labs" asp-action="Lab1">L1</a>
							</li>
							<li class="nav-item">
								<a class="nav-link text-dark" asp-area="" asp-controller="Labs" asp-action="Lab2">L2</a>
							</li>
							<li class="nav-item">
								<a class="nav-link text-dark" asp-area="" asp-controller="Labs" asp-action="Lab3">L3</a>
							</li>
						</ul>
					</div>
				}

				<div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
					@if (User.Identity.IsAuthenticated)
					{
						<ul class="nav navbar-nav navbar-right">
							<li><p class="navbar-text">Hello, @User.Identity.Name </p></li>
							<li><a class="nav-link" asp-controller="Account" asp-action="Profile" id="profile-button">Profile</a></li>
							<li>
								<form class="form-inline" asp-controller="Account" asp-action="SignOut" method="post">
									<button type="submit" class="nav-link btn btn-link text-dark" id="logout-button">Sign Out</button>
								</form>
							</li>
						</ul>
					}
					else
					{
						<ul class="nav navbar-nav navbar-right">
							<li><a class="nav-link" asp-controller="Account" asp-action="SignIn" id="login-button">Sign In</a></li>
						</ul>
					}
				</div>
			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>